### PR TITLE
Fix unduly harsh quiz result messages

### PR DESCRIPTION
**Pull request by rtyley**
The mobile apps have been showing users the quiz result message that corresponds to `score`**`- 1`**. For instance, on this quiz:

* https://www.theguardian.com/uk/quiz/2013/jan/27/british-citizenship-test-quiz-new

...if you complete the quiz with a score of 8 out of 10 correct answers, you get the right score displayed (_"You scored: 8/10"_), but the message shown is the message for 7/10, which includes the phrase _"...on this 10-question test you've come in at **70%**..."_ and exposes the problem:

screenshot

We've had this off-by-one error since the functionality to show the result text was initially added with 102c32bfc, and [a few other users spotted it](https://twitter.com/Open_Book/status/775340704637788160), but obviously it only affects quizzes displaying on the mobile apps (iOS and Android), not the website, tho' that did have https://github.com/guardian/frontend/pull/15276 last year :)

Thanks to avid Guardian reader Michael Goldrei for reporting this issue with a good screenshot and url!

### CODE REVIEW

**Comment by rtyley** [comment]
Great! - I guess I can merge it? I don't know what the deployment process is for this project tho'...

**Comment by GHaberis** [comment]
Yes you can merge into master, it'll kick off a build and automatically update the ios/android projects with the updated templates.

**Comment by rtyley** [comment]
Thanks! Do the apps dynamically load the templates from us, or are they embedded into app releases?

**Comment by alfavata** [comment]
Embedded with each release. We (iOS, not sure about Android) have a remote deploy system but we usually don't do that except for emergency fixes.

**Pull request merged**
