### PR TITLE
GIA-3715 - adding AudioPlay and AudioStop functions to shim

### PR DESCRIPTION
**Pull request by clarehyam**
To fix audio play and stop functions not working on iOS after reloading already playing audio

### CODE REVIEW

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.

**Comment by TormodMacLean** [comment]
:+1: 

It would be good if this could get a quick code review

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.


For a CSS diff, check the wraith gallery [here](http://iosuiauto.gutools.co.uk/view/Mobile%20Templates/job/TemplatesPullRequest/99/CSS_Diff/).

**Pull request merged**
