### PR TITLE
Hide all loading icons when new blocks are inserted

### PR DESCRIPTION
**Pull request by webb04**
@alfavata This has been pushed to https://s3-eu-west-1.amazonaws.com/builds.gutools.co.uk/guardian-mobile-apps-article-templates-v1.0.225.tgz.

Hopefully it works, if not there's two other cases we might need to hide the loading icons.

### CODE REVIEW

**Comment by alfavata** [comment]
Unfortunately I can still see the loading indicator when it should be hidden:

IMG_EF01C17D73AA-1

**Comment by alfavata** [comment]
This doesn't happen consistently: sometimes they're all gone, sometimes I can see 3 of them...

**Comment by alfavata** [comment]
And this is the end state when there should be no more gap at all:

IMG_FED0BD29FCF6-1

**Comment by alfavata** [comment]
Would it help if the native code called a JS function explicitly before inserting the new blocks?

**Comment by alfavata** [comment]
(I think this change has made things worse, if anything - I wasn't seeing that many previosuly...)

**Comment by alfavata** [comment]
@webb04 As discussed, please check out https://github.com/guardian/ios-live/tree/gla-1082-linking-to-liveblog-blocks if you want to experiment with this

**Comment by alfavata** [comment]
The key event are using the colour only for live blogs, not dead ones - not sure if that's what @benwuersching wants?

**Comment by benwuersching** [comment]
@webb04 @alfavata Whenever we show a list of key events linking to the referring blocks, then those links should be in colour (red for news pillar, blue for sport, gold for culture etc). This should be the case in 'live' blogs as well as 'dead' blogs.

**Comment by alfavata** [comment]
I've tested this on Android too and it seems to work very well, I think it's ready to merge!

**Comment by webb04** [comment]
Thanks for reviewing! I'll merge this on Monday and also add the link colours on dark mode.

**Pull request merged**
