### PR TITLE
Add loading state once audio requested

### PR DESCRIPTION
**Pull request by webb04**
Using the existing loading state to show content is loading (this can be quite long, especially on slow 3g/4g connections).

The logic to add a loading state is there so we can update the design to anything else.

Could also animate the play/pause icons to make it less jumpy.

| Current | Suggested |
| --- | --- |
| current | after |

### CODE REVIEW

**Comment by duarte** [comment]
Hey, I think we shouldn't use the roundel here. We should remove the icon, and add a scale animation to the yellow circle (maybe two circles or something). If we hold this, I'll try to do somethin for it next week!

**Comment by webb04** [comment]
Yeah sure, the roundel did look a bit weird there but couldn't find any other loading states within app or website

**Comment by duarte** [comment]
I have an idea for something new we can do with that circle that might be cool

**Comment by duarte** [comment]
I've added the animation now :)
Can we test it on the simulatrion on your laptop?

For reference, it should look like this — https://uploads.guim.co.uk/2018/12/13/Screenflick_Movie_2.mp4

**Comment by webb04** [comment]
It looks good! Me and Jorge spotted a bug with the earlier code changes, maybe we could fix that?

**Comment by webb04** [comment]
We've also got to merge Jorge's PR in

**Comment by webb04** [comment]
There's some js erroring, trying to find out where 😅

**Comment by webb04** [comment]
Ah that's just going between webpack/grunt... looks good! but no longer pulses

**Pull request merged**
