### PR TITLE
AND-3470 - adding new Byline template for when source populated, addi…

### PR DESCRIPTION
**Pull request by clarehyam**
…ng static code to templates, change to byline colour on media from white to grey

### CODE REVIEW

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.


For a CSS diff, check the wraith gallery [here](http://iosuiauto.gutools.co.uk/view/Mobile%20Templates/job/TemplatesPullRequest/54/CSS_Diff/).

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.


For a CSS diff, check the wraith gallery [here](http://iosuiauto.gutools.co.uk/view/Mobile%20Templates/job/TemplatesPullRequest/71/CSS_Diff/).

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.


For a CSS diff, check the wraith gallery [here](http://iosuiauto.gutools.co.uk/view/Mobile%20Templates/job/TemplatesPullRequest/72/CSS_Diff/).

**Comment by christabella76** [comment]
test this please

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.


For a CSS diff, check the wraith gallery [here](http://iosuiauto.gutools.co.uk/view/Mobile%20Templates/job/TemplatesPullRequest/87/CSS_Diff/).

**Pull request merged**
