### PR TITLE
Update instructions for iOS/Android development

### PR DESCRIPTION
**Pull request by alfavata**
I've updated the instructions for mobile apps development to use our preferred method -- comments welcome

CC @GHaberis @SiAdcock @jorgeazevedo @guardian/ios-developers @guardian/android-developers

### CODE REVIEW

**Comment by jorgeazevedo** [comment]
This workflow works for me 👍

**Comment by GHaberis** [comment]
Were there issues with `npm link`? And have we tested that this works as expected? Including building via Xcode? If we've tested it works when building using Xcode and pulls the local templates then I'm happy to 👍  this.

ps. Pull Request ID 666 :metal:

**Comment by jorgeazevedo** [comment]
omg missed it!! 🤘

**Comment by alfavata** [comment]
@GHaberis we have tested this workflow and it works for use. The only concern @fgauchet  had about `npm link` was that it's likely people would forget to unlink 😅

**Pull request merged**
