### PR TITLE
Pull request with issue

### PR DESCRIPTION
**Pull request by jorgeazevedo**
This is a fake pull request to test sonar qube integration.

Jenkins should pickup on the fact that a === has been changed to ==.

### CODE REVIEW

**Comment by jorgeazevedo** [comment]
test this please

**Comment by jorgeazevedo** [comment]
test this please

**Comment by jorgeazevedo** [comment]
test this please

**Comment by jorgeazevedo** [comment]
test this please

**Comment by jorgeazevedo** [comment]
test this please

**Comment by jorgeazevedo** [comment]
test this please

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.

**Comment by jorgeazevedo** [comment]
test this please

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 1 issues.

* 1 major issue(s): 
 * Replace "==" with "===".

For further information, check the SonarQube issues page [here](http://mobbld.gutools.co.uk:9000/component_issues/index?id=34407#createdAfter=2015-04-29T15:32:44%2B0100)

**Comment by jorgeazevedo** [comment]
test this please

**Comment by jorgeazevedo** [comment]
test this please

**Comment by jorgeazevedo** [comment]
test this please

**Comment by jorgeazevedo** [comment]
test this please

**Comment by jorgeazevedo** [comment]
test this please

**Comment by jorgeazevedo** [comment]
test this please

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 1 issues.

* 1 major issue(s): 
 * Replace "==" with "===".

For further information, check the SonarQube issues page [here](http://mobbld.gutools.co.uk:9000/component_issues/index?id=34407#createdAfter=2015-05-01T11:27:40%2B0100)

**Pull request closed without merging**
