### PR TITLE
Change article header bgcolor to shade-1

### PR DESCRIPTION
**Pull request by jorgeazevedo**
Please ignore, I'm testing wraith

### CODE REVIEW

**Comment by jorgeazevedo** [comment]
jenkins test this please

**Comment by jorgeazevedo** [comment]
jenkins test this please

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.

**Comment by jorgeazevedo** [comment]
jenkins test this please

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.

**Comment by jorgeazevedo** [comment]
jenkins test this please

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.

**Comment by jorgeazevedo** [comment]
jenkins test this please

**Comment by jorgeazevedo** [comment]
jenkins test this please

**Comment by jorgeazevedo** [comment]
jenkins test this please

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.

**Comment by jorgeazevedo** [comment]
jenkins test this please

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.


For a CSS diff, check the wraith gallery [here](http://iosuiauto.gutools.co.uk/view/Mobile%20Templates/job/TemplatesPullRequest/43/CSS_Diff/).

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.


For a CSS diff, check the wraith gallery [here](http://iosuiauto.gutools.co.uk/view/Mobile%20Templates/job/TemplatesPullRequest/44/CSS_Diff/).

**Comment by jorgeazevedo** [comment]
jenkins test this please

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.


For a CSS diff, check the wraith gallery [here](http://iosuiauto.gutools.co.uk/view/Mobile%20Templates/job/TemplatesPullRequest/50/CSS_Diff/).

**Pull request closed without merging**
