### PR TITLE
Remove lodash debounce

### PR DESCRIPTION
**Pull request by GHaberis**
Replace with debounce method in util.js

### CODE REVIEW

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 4 issues.

* 3 minor issue(s): 
 * Remove the useless trailing whitespaces at the end of this line.
 * Remove the useless trailing whitespaces at the end of this line.
 * Remove the useless trailing whitespaces at the end of this line.
* 1 major issue(s): 
 * This function has 114 lines, which is greater than the 100 lines authorized. Split it into smaller functions.

For further information, check the SonarQube issues page [here](http://ec2-54-194-92-131.eu-west-1.compute.amazonaws.com:9000/component_issues/index?id=468482#createdAfter=2016-05-20T17:11:21%2B0100).

For a CSS diff, check the wraith gallery [here](http://iosuiauto.gutools.co.uk:8080/view/Mobile%20Templates/job/TemplatesPullRequest/178/CSS_Diff/).

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 4 issues.

* 3 minor issue(s): 
 * Remove the useless trailing whitespaces at the end of this line.
 * Remove the useless trailing whitespaces at the end of this line.
 * Remove the useless trailing whitespaces at the end of this line.
* 1 major issue(s): 
 * This function has 114 lines, which is greater than the 100 lines authorized. Split it into smaller functions.

For further information, check the SonarQube issues page [here](http://ec2-54-194-92-131.eu-west-1.compute.amazonaws.com:9000/component_issues/index?id=468482#createdAfter=2016-05-23T09:32:57%2B0100).

For a CSS diff, check the wraith gallery [here](http://iosuiauto.gutools.co.uk:8080/view/Mobile%20Templates/job/TemplatesPullRequest/179/CSS_Diff/).

**Comment by gtrufitt** [comment]
👍 🚢

**Comment by GHaberis** [comment]
@gtrufitt thanks!

**Pull request merged**
