### PR TITLE
And 10029

### PR DESCRIPTION
**Pull request by christabella76**
Client side work required for Android (Jira ticket AND-10029) and iOS (Jira ticket GIA-3870).

### CODE REVIEW

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.

**Comment by jorgeazevedo** [comment]
jenkins test this please

**Comment by jorgeazevedo** [comment]
jenkins test this please

**Comment by jorgeazevedo** [comment]
jenkins test this please

**Comment by jorgeazevedo** [comment]
jenkins test this please

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.


For a CSS diff, check the wraith gallery [here](http://iosuiauto.gutools.co.uk/view/Mobile%20Templates/job/TemplatesPullRequest/49/CSS_Diff/).

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.


For a CSS diff, check the wraith gallery [here](http://iosuiauto.gutools.co.uk/view/Mobile%20Templates/job/TemplatesPullRequest/53/CSS_Diff/).

**Comment by christabella76** [comment]
Test this please

**Comment by christabella76** [comment]
Test this please

**Comment by jorgeazevedo** [comment]
test this please

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.


For a CSS diff, check the wraith gallery [here](http://iosuiauto.gutools.co.uk/view/Mobile%20Templates/job/TemplatesPullRequest/85/CSS_Diff/).

**Pull request merged**
