### PR TITLE
AND-10152: Get article content height

### PR DESCRIPTION
**Pull request by AleLudovici**

### CODE REVIEW

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 1 issues.

* 1 minor issue(s): 
 * Remove the useless trailing whitespaces at the end of this line.

For further information, check the SonarQube issues page [here](http://ec2-54-154-49-20.eu-west-1.compute.amazonaws.com:9000/component_issues/index?id=72456#createdAfter=2015-08-20T16:02:00%2B0000)

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 1 issues.

* 1 minor issue(s): 
 * Remove the useless trailing whitespaces at the end of this line.

For further information, check the SonarQube issues page [here](http://ec2-54-154-49-20.eu-west-1.compute.amazonaws.com:9000/component_issues/index?id=72456#createdAfter=2015-08-24T10:02:45%2B0000)

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 1 issues.

* 1 minor issue(s): 
 * Remove the useless trailing whitespaces at the end of this line.

For further information, check the SonarQube issues page [here](http://ec2-54-154-49-20.eu-west-1.compute.amazonaws.com:9000/component_issues/index?id=72456#createdAfter=2015-08-24T11:03:27%2B0000)

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 1 issues.

* 1 minor issue(s): 
 * Remove the useless trailing whitespaces at the end of this line.

For further information, check the SonarQube issues page [here](http://ec2-54-154-49-20.eu-west-1.compute.amazonaws.com:9000/component_issues/index?id=72456#createdAfter=2015-08-24T14:01:50%2B0000)

**Comment by christabella76** [comment]
Test this please

**Comment by jorgeazevedo** [comment]
test this please

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 1 issues.

* 1 blocker issue(s): 
 * Avoid trailing comma in array and object literals.

For further information, check the SonarQube issues page [here](http://ec2-54-154-49-20.eu-west-1.compute.amazonaws.com:9000/component_issues/index?id=1095#createdAfter=2015-09-23T09:22:17%2B0000).

For a CSS diff, check the wraith gallery [here](http://iosuiauto.gutools.co.uk/view/Mobile%20Templates/job/TemplatesPullRequest/86/CSS_Diff/).

**Pull request merged**
