### PR TITLE
And 3762 - Follow Contributors Design amends 

### PR DESCRIPTION
**Pull request by clarehyam**

### CODE REVIEW

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.

**Comment by GuardianAndroid** [comment]
SonarQube has found a total of 0 issues.

**Comment by glockett** [comment]
QA :+1:   Checked Android - all OK and also looked on iOS to verify that nothing was broken

**Pull request merged**
