### PR TITLE
Fixed missing kicker in live blogs

### PR DESCRIPTION
**Pull request by tkgnm**
This fixes a bug where the kicker was missing from some live blogs. On line 41 in the` liveBlogTemplate.html` file we are displaying the `__SERIES__` as the kicker. The problem is, not every live blog will be part of a series. In these cases we need to revert to displaying the `__SECTION__` so that we are in line with the website. 

Jamie Byers has mentioned that there are some slightly more complicated rules around what to display as the "kicker" on Dotcom and therefore this change isn't necessarily "perfect". However, it should still cover the large majority of cases and will mean there is no more blank space where there should be a kicker. In any case, it probably isn't worth spending too much time on as the Apps Rendering rollout will make these templates obsolete in the near future. 

| Before | After |
| --- | --- |
|||

### CODE REVIEW

**Review by idrise — APPROVED** [review]
With a nice function name to describe intent. Nice.

**Review by marjisound — APPROVED** [review]
Great work, just had a question but feel free to merge :)

**Comment by marjisound** [comment]
@tkgnm Did you have a reason to put this js within the html rather than the liveblog.js or another relevant js file?

**Review by sophie-macmillan — APPROVED** [review]

**Review by marjisound — APPROVED** [review]
Great work Tom 👏

**Pull request merged**
