### PR TITLE
Remove pre garnett assets

### PR DESCRIPTION
**Pull request by webb04**
⚠️ Needs testing before merging. Would be good to wait until next app releases.

- Removes contents of old styles-sync.css
- Removes contents of old styles-async.css
- Remove classes of "show-garnett"
- Merge duplicated sass folders (e.g. "garnett-layout" and "layout")

### CODE REVIEW

**Comment by SLambrakis** [comment]
@webb04 For iOS the first build of v7.0 will be going to beta on Friday, so if you can get this merged before then it'll get a while in beta.

**Comment by webb04** [comment]
@SLambrakis Thanks, I'll test before merging but would be good to have in beta for a while.

**Comment by SiAdcock** [comment]
screen shot 2018-08-23 at 14 02 36

💎 💎 💎 💎

**Comment by alfavata** [comment]
We're going to do a beta very soon, is this ready to merge?

**Comment by GHaberis** [comment]
I'd remove the `garnett-` prefix from the `scss` folders, there's no need to have this here now.

**Comment by GHaberis** [comment]
Great to see all this unused code being removed! There are a few more things that could be done alongside this.

- Remove the `garnett-` prefix from the `scss` folders, there's no need to have this here now.
- Update the `Grunt` config to no-longer build the following assets:

```js
'ArticleTemplates/assets/css/garnett-style-async.css'
 'ArticleTemplates/assets/css/garnett-style-sync.css'
```

It could just build 2 `css ` files named:

```js
'ArticleTemplates/assets/css/style-async.css'
 'ArticleTemplates/assets/css/style-sync.css'
```

- Replace `__SYNC_STYLES__` in all HTML templates `style-sync`
- Replace `__ASYNC_STYLES__` in all HTML templates `style-async`

**Pull request merged**
