### PR TITLE
Templates media controls 

### PR DESCRIPTION
**Pull request by webb04**

### CODE REVIEW

**Comment by webb04** [comment]
Native pull requests also opened for fronts.

**Comment by duarte** [comment]
Thanks for this Jamie, colours look good! Does the 'played' (left) section of the audio scrubber go yellow too?

Do you wanna merge this in, or will you attempt for the boss level?

**Comment by webb04** [comment]
screen shot 2018-10-09 at 10 42 44

**Comment by webb04** [comment]
Starts without *-*
screen shot 2018-10-09 at 12 45 43

**Pull request merged**
