### PR TITLE
Sad icon added :(

### PR DESCRIPTION
**Pull request by superfrank**
Added search icon with sadface for 'Search' page.
image

### CODE REVIEW

**Comment by sandropaganotti** [comment]
:+1: 

sad sad

**Comment by superfrank** [comment]
haha, YES SANDRO. My first commit. I am no longer a virgin.

On Tue, Feb 17, 2015 at 12:13 PM, Sandro Paganotti <notifications@github.com

**Comment by Odhran** [comment]
You took your sweet time Frank. :+1:

**Comment by superfrank** [comment]
Was worth the wait though...right!?

**Comment by sandropaganotti** [comment]
yup! ^_^ :+1:

**Pull request merged**
