### PR TITLE
Replace outdated font files

### PR DESCRIPTION
**Pull request by duarte**
Updates Guardian Headline font files to the latest version…

CC @paperboyo

### CODE REVIEW

**Comment by mchv** [comment]
@paperboyo I think this is one step completed of https://github.com/guardian/frontend/issues/19550

**Comment by paperboyo** [comment]
Unfortunately, no @mchv. This is just fixing omission (using beta version of the GH Guardian Headline fonts here). The above PR is about upgrading Guardian Egyptian and Sans Text fonts: it is separate job.

**Comment by maxspencer** [comment]
We no longer use the fonts packaged with the templates, we bundle them natively. I can take the files included here and make the same change in the `android-news-app` repo.

**Comment by paperboyo** [comment]
> We no longer use the fonts packaged with the templates, we bundle them natively.

Thanks for letting me know, @maxspencer, very useful! Could you also synchronise with iOS (and, IMHO, with dotcom) on https://github.com/guardian/mobile-apps-article-templates/pull/813#issuecomment-408833374, please? Ideally, we would have just one set, but if you Guys decide differently, we should have two, not three!

Plus, just a small win-wink-nudge-nudge about mentioned https://github.com/guardian/frontend/issues/19550.

**Comment by alfavata** [comment]
Yes please, we'd be very keen to share our fonts with the template layer too!
(I believe @jorgeazevedo has this on his roadmap too)

**Comment by alfavata** [comment]
I've created a [Tech Debt ticket](https://theguardian.atlassian.net/browse/GLA-870) in our Jira backlog.

**Pull request merged**
